// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXtjyjGFxXshk-_96t6DJ6IdzsBeWROo',
    appId: '1:644374551484:web:02d313759565ad32e1a9b9',
    messagingSenderId: '644374551484',
    projectId: 'cargocollectionmanagement',
    authDomain: 'cargocollectionmanagement.firebaseapp.com',
    storageBucket: 'cargocollectionmanagement.firebasestorage.app',
    measurementId: 'G-9VG6W82ZLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWz9iVtWfzHOEjQRUQ59VulO4tpN06Ps',
    appId: '1:644374551484:android:1b908de71486814de1a9b9',
    messagingSenderId: '644374551484',
    projectId: 'cargocollectionmanagement',
    storageBucket: 'cargocollectionmanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5PgEcdLhyBlUpaxW1yIXq8e-BGYKa46s',
    appId: '1:644374551484:ios:dba6b0f7ac6a3ac2e1a9b9',
    messagingSenderId: '644374551484',
    projectId: 'cargocollectionmanagement',
    storageBucket: 'cargocollectionmanagement.firebasestorage.app',
    iosBundleId: 'com.example.cargocollectionmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5PgEcdLhyBlUpaxW1yIXq8e-BGYKa46s',
    appId: '1:644374551484:ios:dba6b0f7ac6a3ac2e1a9b9',
    messagingSenderId: '644374551484',
    projectId: 'cargocollectionmanagement',
    storageBucket: 'cargocollectionmanagement.firebasestorage.app',
    iosBundleId: 'com.example.cargocollectionmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqXtjyjGFxXshk-_96t6DJ6IdzsBeWROo',
    appId: '1:644374551484:web:e13ff2a428b8d3dbe1a9b9',
    messagingSenderId: '644374551484',
    projectId: 'cargocollectionmanagement',
    authDomain: 'cargocollectionmanagement.firebaseapp.com',
    storageBucket: 'cargocollectionmanagement.firebasestorage.app',
    measurementId: 'G-E0X0KRLXF6',
  );
}